/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type VideoId = string;
export interface VideoMetadata {
  'id' : VideoId,
  'status' : VideoStatus,
  'contentType' : string,
  'owner' : VideoOwner,
  'size' : bigint,
  'fileName' : string,
  'watermark' : [] | [WatermarkInfo],
  'uploadedAt' : Time,
}
export type VideoOwner = Principal;
export type VideoStatus = { 'deleted' : null } |
  { 'completed' : null } |
  { 'uploaded' : null } |
  { 'processing' : null } |
  { 'failed' : null };
export interface WatermarkInfo {
  'x' : bigint,
  'y' : bigint,
  'height' : bigint,
  'width' : bigint,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteVideo' : ActorMethod<[string, VideoId], boolean>,
  'getAllVideosByOwner' : ActorMethod<
    [string, Principal],
    Array<VideoMetadata>
  >,
  'getCallerUserProfile' : ActorMethod<[string], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getUserProfile' : ActorMethod<[string, Principal], [] | [UserProfile]>,
  'getVideo' : ActorMethod<[string, VideoId], [] | [VideoMetadata]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markWatermark' : ActorMethod<
    [string, VideoId, bigint, bigint, bigint, bigint],
    boolean
  >,
  'saveCallerUserProfile' : ActorMethod<[string, UserProfile], undefined>,
  'updateVideoStatus' : ActorMethod<[string, VideoId, VideoStatus], boolean>,
  'uploadVideo' : ActorMethod<[string, string, string, bigint], VideoId>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];