/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const VideoId = IDL.Text;
export const VideoStatus = IDL.Variant({
  'deleted' : IDL.Null,
  'completed' : IDL.Null,
  'uploaded' : IDL.Null,
  'processing' : IDL.Null,
  'failed' : IDL.Null,
});
export const VideoOwner = IDL.Principal;
export const WatermarkInfo = IDL.Record({
  'x' : IDL.Nat,
  'y' : IDL.Nat,
  'height' : IDL.Nat,
  'width' : IDL.Nat,
});
export const Time = IDL.Int;
export const VideoMetadata = IDL.Record({
  'id' : VideoId,
  'status' : VideoStatus,
  'contentType' : IDL.Text,
  'owner' : VideoOwner,
  'size' : IDL.Nat,
  'fileName' : IDL.Text,
  'watermark' : IDL.Opt(WatermarkInfo),
  'uploadedAt' : Time,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteVideo' : IDL.Func([IDL.Text, VideoId], [IDL.Bool], []),
  'getAllVideosByOwner' : IDL.Func(
      [IDL.Text, IDL.Principal],
      [IDL.Vec(VideoMetadata)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Text, IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVideo' : IDL.Func(
      [IDL.Text, VideoId],
      [IDL.Opt(VideoMetadata)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markWatermark' : IDL.Func(
      [IDL.Text, VideoId, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
      [IDL.Bool],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([IDL.Text, UserProfile], [], []),
  'updateVideoStatus' : IDL.Func(
      [IDL.Text, VideoId, VideoStatus],
      [IDL.Bool],
      [],
    ),
  'uploadVideo' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [VideoId],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const VideoId = IDL.Text;
  const VideoStatus = IDL.Variant({
    'deleted' : IDL.Null,
    'completed' : IDL.Null,
    'uploaded' : IDL.Null,
    'processing' : IDL.Null,
    'failed' : IDL.Null,
  });
  const VideoOwner = IDL.Principal;
  const WatermarkInfo = IDL.Record({
    'x' : IDL.Nat,
    'y' : IDL.Nat,
    'height' : IDL.Nat,
    'width' : IDL.Nat,
  });
  const Time = IDL.Int;
  const VideoMetadata = IDL.Record({
    'id' : VideoId,
    'status' : VideoStatus,
    'contentType' : IDL.Text,
    'owner' : VideoOwner,
    'size' : IDL.Nat,
    'fileName' : IDL.Text,
    'watermark' : IDL.Opt(WatermarkInfo),
    'uploadedAt' : Time,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteVideo' : IDL.Func([IDL.Text, VideoId], [IDL.Bool], []),
    'getAllVideosByOwner' : IDL.Func(
        [IDL.Text, IDL.Principal],
        [IDL.Vec(VideoMetadata)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Text, IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVideo' : IDL.Func(
        [IDL.Text, VideoId],
        [IDL.Opt(VideoMetadata)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markWatermark' : IDL.Func(
        [IDL.Text, VideoId, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
        [IDL.Bool],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([IDL.Text, UserProfile], [], []),
    'updateVideoStatus' : IDL.Func(
        [IDL.Text, VideoId, VideoStatus],
        [IDL.Bool],
        [],
      ),
    'uploadVideo' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [VideoId],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };